### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by SAYREXx** [jackdevonshire/Arma-3-Scripts#1]
Where can I get the "hint" you are using?
`F(hint,ANYONE)`

**Comment by jackdevonshire** [comment]
Hi, I'm not sure I understand your question. If it is in regard to the Waypoints Framework, adding 'F(hint,ANYONE)' to CFGRemoteExec.hpp under the 'Functions for Everyone comment' allows for the default Arma "hint '';" to be triggered by one player, but for another player.

The bulk of the war points script is triggered on the victim's side, so the victim essentially remote calls the hint command on the killer's computer, hence the remote exec file needs to be updated.

If I haven't explained it very well, or you need some help just drop me a way I can connect with you - Discord maybe?

To be honest, I forgot about these scripts, I've been so busy lately. I will update them and patch any bugs when I am next free.

**Comment by SAYREXx** [comment]
Yes, thanks, I understood everything
